import z from "zod";

export const weatherSchema = z.object({
  location: z.object({
    name: z.string(),
    region: z.string(),
    country: z.string(),
    lat: z.number(),
    lon: z.number(),
    tz_id: z.string(),
    localtime_epoch: z.number(),
    localtime: z.string(),
  }),
  current: z.object({
    last_updated_epoch: z.number(),
    last_updated: z.string(),
    temp_c: z.number(),
    condition: z.object({
      text: z.string(),
      icon: z.string(),
      code: z.number(),
    }),
    wind_kph: z.number(),
    wind_degree: z.number(),
    wind_dir: z.string(),
    pressure_mb: z.number(),
    precip_mm: z.number(),
    humidity: z.number(),
    cloud: z.number(),
    feelslike_c: z.number(),
    dewpoint_c: z.number(),
    vis_km: z.number(),
    uv: z.number(),
    gust_kph: z.number(),
    air_quality: z.object({
      co: z.number(),
      no2: z.number(),
      o3: z.number(),
      so2: z.number(),
      pm2_5: z.number(),
      pm10: z.number(),
      "us-epa-index": z.number(),
      "gb-defra-index": z.number(),
    }),
  }),
  forecast: z.object({
    forecastday: z.array(
      z.object({
        date: z.string(),
        date_epoch: z.number(),
        day: z.object({
          maxtemp_c: z.number(),
          mintemp_c: z.number(),
          avgtemp_c: z.number(),
          maxwind_kph: z.number(),
          totalprecip_mm: z.number(),
          avgvis_km: z.number(),
          avghumidity: z.number(),
          condition: z.object({
            text: z.string(),
            icon: z.string(),
            code: z.number(),
          }),
          uv: z.number(),
        }),
        astro: z.object({
          sunrise: z.string(),
          sunset: z.string(),
          moonrise: z.string(),
          moonset: z.string(),
          moon_phase: z.string(),
        }),
        hour: z.array(
          z.object({
            time_epoch: z.number(),
            time: z.string(),
            temp_c: z.number(),
            condition: z.object({
              text: z.string(),
              icon: z.string(),
              code: z.number(),
            }),
            wind_kph: z.number(),
            wind_degree: z.number(),
            wind_dir: z.string(),
            pressure_mb: z.number(),
            precip_mm: z.number(),
            humidity: z.number(),
            cloud: z.number(),
            feelslike_c: z.number(),
            dewpoint_c: z.number(),
            vis_km: z.number(),
            gust_kph: z.number(),
            uv: z.number(),
          }),
        ),
      }),
    ),
  }),
});
